### ISSUE TITLE
Use Src directory instead of lob in all examples

### ISSUE THREAD

**Issue by leore** [lob/lob-python#95]

**Comment by elnaz** [comment]
Can you provide some more context on this? Using `import lob` makes the examples more realistic to how a user would utilize this package in their own projects.

**Comment by leore** [comment]
Talked IRL. Makes sense

**Comment by dmlittle** [comment]
The `sys.path.insert(...)` make sure to use the local lob package rather than the one installed through pip. If it can't find the local package, it will fallback to the pip installed package. The examples will working without installing the local package so long as you don't move them to a different folder.
https://github.com/lob/lob-python/blob/a8a5a71f7ffa58c02774578671c3e7f1992f4eec/examples/postcard.py#L2

**Comment by mgartner** [comment]
So it sounds like this is a non-issue then? Can we close?
